apiVersion: apps/v1
kind: Deployment
metadata:
  name: two-v1
  namespace: istio-example
  labels:
    app: two
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: two
      version: v1
  template:
    metadata:
      labels:
        app: two
        version: v1
    spec:
      containers:
        - name: two-v1
          image: registry.prod.bbdops.com/common/two-v1:v0.0.3
          ports:
            - containerPort: 8002

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: two-v2
  namespace: istio-example
  labels:
    app: two
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: two
      version: v2
  template:
    metadata:
      labels:
        app: two
        version: v2
    spec:
      containers:
        - name: two-v2
          image: registry.prod.bbdops.com/common/two-v2:v0.0.3
          ports:
            - containerPort: 8002