apiVersion: apps/v1
kind: Deployment
metadata:
  name: one-v1
  namespace: istio-example
  labels:
    app: one
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: one
      version: v1
  template:
    metadata:
      labels:
        app: one
        version: v1
    spec:
      containers:
        - name: one-v1
          image: registry.prod.bbdops.com/common/one-v1:v0.0.3
          ports:
            - containerPort: 8001

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: one-v2
  namespace: istio-example
  labels:
    app: one
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: one
      version: v2
  template:
    metadata:
      labels:
        app: one
        version: v2
    spec:
      containers:
        - name: one-v2
          image: registry.prod.bbdops.com/common/one-v2:v0.0.3
          ports:
            - containerPort: 8001